# ZERO R CLASSIFIER

## Imports and Settings

In [46]:
import numpy as np 
import scipy as sp 
from sklearn import datasets
from sklearn.model_selection import cross_val_predict, cross_val_score
from sklearn.dummy import DummyClassifier
from sklearn.metrics import confusion_matrix, plot_confusion_matrix
import matplotlib.pyplot as plt

In [28]:
num_folds = 10
num_rep = 3

## Código

### Leitura do dataset

In [10]:
wine_ds = datasets.load_wine()

wine_x = wine_ds.data
wine_y = wine_ds.target

### Configuração do classificador

In [17]:
zero_r = DummyClassifier(strategy='stratified')

### Classificação


In [29]:
predicts = []

for i in range(num_rep):
    predicts.append(cross_val_predict(zero_r, wine_x, wine_y, cv=folds))


### Resultados

In [50]:
for i in range(num_rep):
    score = cross_val_score(zero_r, wine_x, wine_y, scoring='accuracy', cv=folds)
    print(score)
    conf_matrix = (confusion_matrix(wine_y, predicts[i]))
    print("\nMatriz de confusão:")
    print(conf_matrix)
    
    # plt.matshow(conf_matrix, cmap=plt.cm.Blues)
    # for i in range(len(conf_matrix)):
    #    for j in range(len(conf_matrix)):
    #        plt.text(i, j, conf_matrix[i][j], va="center", ha="center")

[0.44444444 0.61111111 0.61111111 0.27777778 0.27777778 0.44444444
 0.44444444 0.38888889 0.47058824 0.17647059]

Matriz de confusão:
[[19 26 14]
 [20 29 22]
 [14 22 12]]
[0.55555556 0.22222222 0.33333333 0.44444444 0.33333333 0.22222222
 0.33333333 0.22222222 0.41176471 0.41176471]

Matriz de confusão:
[[17 27 15]
 [16 32 23]
 [17 16 15]]
[0.33333333 0.22222222 0.38888889 0.5        0.33333333 0.27777778
 0.38888889 0.33333333 0.41176471 0.17647059]

Matriz de confusão:
[[20 29 10]
 [20 35 16]
 [ 9 19 20]]
